#!/usr/bin/env bash
# configures an Nginx server to listen on port 80.

# creates a symbolic link (-s option) between the Nginx configuration file
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminate the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
sudo service nginx stop
